Refactor

diff --git a/craftinginterpreters/Makefile b/craftinginterpreters/Makefile
--- a/craftinginterpreters/Makefile
+++ b/craftinginterpreters/Makefile
@@ -1,8 +1,9 @@
 CC      = zig cc
-CFLAGS = -std=c23 -Wall -Wextra -Wpedantic -O2 -g \
-         -fsanitize=address,undefined
+CFLAGS_RELEASE = -std=c23 -O2 -DNDEBUG -fno-omit-frame-pointer
+
 CFLAGS_DEBUG = -std=c23 -Wall -Wextra -Wpedantic -Og -g \
-               -fsanitize=address,undefined
+-fsanitize=address,undefined -fno-omit-frame-pointer
+
 TARGET  = build/lox
 SRC     = src/main.c src/arena.c src/lox.c src/debug.c src/expr.c src/parser.c src/scanner.c src/stmt.c
 TEST_TARGET = build/test
@@ -10,21 +11,23 @@ TEST_SRC     = src/test.c src/arena.c src/lox.c src/debug.c src/expr.c src/parse
 
 .PHONY: all run clean test
 
-all: $(TARGET)
+clean:
+	rm -f $(TARGET) $(TEST_TARGET)
+
+all: $(clean) $(TARGET)
 
 $(TARGET): $(SRC)
 	@mkdir -p build
-	$(CC) $(CFLAGS) -o $(TARGET) $(SRC)
+	$(CC) $(CFLAGS_RELEASE) -o $(TARGET) $(SRC) || { echo "Build failed! Exiting..."; exit 1; }
 
-run: $(TARGET)
+run: $(clean) $(TARGET)
 	./$(TARGET) $(FILE)
 
 $(TEST_TARGET): $(TEST_SRC)
 	@mkdir -p build
-	$(CC) $(CFLAGS) -o $(TEST_TARGET) $(TEST_SRC)
+	$(CC) $(CFLAGS_DEBUG) -o $(TEST_TARGET) $(TEST_SRC) || { echo "Test build failed! Exiting..."; exit 1; }
 
-test: $(TEST_TARGET)
-	./$(TEST_TARGET) > test/test.txt
-    
-clean:
-	rm -f $(TARGET) $(TEST_TARGET)
+# Test rule modification to ensure error reporting if test fails
+test: ${clean} $(TEST_TARGET)
+	@mkdir -p test
+	./$(TEST_TARGET) > test/test.txt || { echo "Tests failed!"; exit 1; }
